### ISSUE TITLE
Buggy graphics when configuration is corrupt.

### ISSUE THREAD

**Issue by GreeniusGenius** [Tellinq/Potion-Effects#16]
Certain textures begin to flash, my screen gets tinted red, massive FPS drops / stutters, etc.
[See video](https://www.icloud.com/iclouddrive/077GBbWQDu0B71ePsheKkY8PA#Screen_Recording_2023-09-10_at_11.59)

As I would eventually find out, this was because the configuration was corrupted, and it had regenerated a new config, that was clearly still corrupt as it causes the aforementioned buggy graphics.
[See archived files.](https://github.com/Tellinq/Potion-Effects/files/12568074/CorruptedConfig.zip)

[See fml-client-latest.log](https://mclo.gs/lLvhLD3)

LWJGL 2.9.4-nightly-20150209
Minecraft 1.8.9
Forge 11.15.1.2318
Azul Zulu OpenJDK [8] 1.8.0_382 aarch64

Optifine preview 1.8.9 HD U M6 pre2

macOS 14.0 Beta 23A5337a arm64
MacBook Pro (14-inch, 2021)
Kernel 23.0.0
Apple M1 Pro (binned)
16gb Memory

The problem was solved by rolling back to a non corrupt config json from a Time Machine backup (or by deleting the new json files that were supposed to be not corrupt, and restarting the game.)

**Comment by Tellinq** [comment]
This is an issue that is not relevant to Potion Effects. The main reason this happens is because of how OneConfig handles Pages. Once a new version modifies something regarding a page, the config corrupts.

While you could say that this would logically only happen with Potion Effects, which is somewhat true at this time, but that's just because I'm one of the few people who takes advantages of Pages.

Please report this to https://github.com/Polyfrost/OneConfig
