### ISSUE TITLE
Potion Effects HUD game crashes and visual bugs

### ISSUE THREAD

**Issue by mqtrx** [Tellinq/Potion-Effects#23]
Anytime I would try to edit my Hud via OneConfig when the mod is enabled, my game would just crash, except for when the mod is disabled. Also the mod causes visual bugs when in a server, visual bugs such as; All entities and semi transparent blocks like glass would clip in and out of existence, and some EverGreenHud mods turning off.

I tried quite a few things to hopefully fix it but nothing worked, I tried disabling other mods, disabling **all** mods, switching from graalvm to regular javaw, turning my computer off and on again but to no avail.

**Comment by Tellinq** [comment]
This is not a Potion Effects issue. Upgrading from older versions will cause your config to go corrupt due to my changes with Pages either not existing anymore or simply changed.

Since this is purely a config issue, you have to redirect this to the official OneConfig repository. While you can make the argument “but it only happens on Potion Effects”, well, I’m the only one who made regular changes to Pages in the past, but that doesn’t make it my issue.

**Comment by Tellinq** [comment]
Please report this to https://github.com/Polyfrost/OneConfig
