### ISSUE TITLE
how do i disable a effect in this potion effect mod like i wanna disable a effect but i dont know how

### ISSUE THREAD

**Issue by karkory555** [Tellinq/Potion-Effects#6]

**Comment by Tellinq** [comment]
Go in the effects tab then for each effect, click the override button. Scroll down until you see "Exclude". That will outright disable an effect from showing 

Main reason it is like this instead of a simple Enable/Disable button at the top is because you can use this toggle to also outright exclude global effects.

Eventually this may be changed to where there will be a specific rule system when you can select multiple effects or type of effects at once and then you can exclude/disable all the ones you want instead of just going into each effect menu.

Hope this helps!

**Comment by karkory555** [comment]
Thanks!
